global:
  resolve_timeout: 5m
  smtp_hello: localhost
  smtp_require_tls: true

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 3600s
  receiver: 'email'

receivers:
- name: 'email'
  email_configs:
  - to: 'painkiller.nhat@gmail.com'
    from: 'hikari.helloworld@gmail.com'
    smarthost: smtp.gmail.com:587
    auth_username: 'hikari.helloworld@gmail.com'
    auth_password: 'eulbkypprvmbtzfn'
    auth_identity: 'hikari.helloworld@gmail.com'
    headers:
      Subject: '{{ template "email.default.subject" . }}'