version: '3.7'

services:
  prometheus:
    image: prom/prometheus:v2.45.0
    volumes:
      # bind mount: prometheus dir
      - ./prometheus/:/etc/prometheus/
    ports:
      - 9090:9090
    networks:
      - prom
    restart: always
  
  alertmanager:
    image: prom/alertmanager:v0.25.0
    volumes:
      - ./alertmanager/:/etc/alertmanager/
    ports:
      - 9093:9093
    networks:
      - prom
    restart: always

  # grafana:
  #   image:
  #   volumes:

  #   command:
  #   ports:
  #     - 3000
  #   depends_on:
  #     - prometheus
  #   networks:
  #     - prom
  #   restart: always

networks:
  prom: