version: '3'
services:
    odoo:
        build:
            context: .
            dockerfile: Dockerfile
        restart: always
        volumes:
            - odoo_data:/opt/odoo/.local/share/Odoo
        links:
            - db:db
        depends_on:
            - db
        deploy:
            replicas: 2
        tty: true
 
    nginx:
        build: .
        container_name: nginx
        image: nginx
        ports:
            - 80:80
        volumes:
            - ./config/nginx:/etc/nginx/conf.d
        expose:
            - 80
        depends_on:
            - odoo

    postgres:
        container_name: postgres
        image: postgres:13
        restart: unless-stopped
        environment:
            POSTGRES_PASSWORD: odoo
            POSTGRES_HOST_AUTH_METHOD: trust
        ports:
            - '5555:5432'
        volumes:
            - ./postgresql:/docker-entrypoint-initdb.d/
        tty: true
    
volumes:
    odoo_data:
    postgresql:
