version: '3.7'
services:
    odoo:
        build:
            context: .
            dockerfile: odoo.Dockerfile
        restart: always
        volumes:
            - odoo_data:/opt/odoo/.local/share/Odoo
        links:
            - postgres:postgres
        depends_on:
            - postgres
        deploy:
            replicas: 2
        tty: true

    nginx:
        build: .
        container_name: nginx
        image: nginx
        volumes:
            - ./nginx/:/etc/nginx/conf.d/
        expose:
            - 80
        depends_on:
            - odoo

    postgres:
        container_name: postgres
        image: postgres:13
        restart: unless-stopped
        environment:
            POSTGRES_PASSWORD: odoo
            POSTGRES_HOST_AUTH_METHOD: trust
        ports:
            - 5433
        volumes:
            - ./postgresql/:/docker-entrypoint-initdb.d/
        tty: true
    
volumes:
    odoo_data:
    postgresql:
