version: '3.7'

services:
  prometheus:
    image: prom/prometheus:v2.45.0
    volumes:
      # bind mount: prometheus dir
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090
    networks:
      - prom
    restart: always
  
  # alertmanager:
  #   image: quay.io/prometheus/alertmanager
  #   volumes:
  #     - ./alertmanager/:/etc/alertmanager/
  #   ports:
  #     - 9093:9093
  #   networks:
  #     - prom
  #   restart: always

  grafana:
    image: grafana/grafana:10.0.3
    volumes:
      - grafana_data:/var/lib/grafana
    ports:
      - 3000:3000
    depends_on:
      - prometheus
    env_file:
      - ./grafana/config.monitoring
    networks:
      - prom
    restart: always

volumes:
  prometheus_data: {}
  grafana_data: {}

networks:
  prom: