# my global config
global:
  scrape_interval:     15s
  evaluation_interval: 15s
 
rule_files:
  - alert.yml
  - odoo.yml

# alert
alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
      - "alertmanager:9093"

scrape_configs:
  
  - job_name: 'prometheus'
    scrape_interval: 15s
    static_configs:
      - targets: ['localhost:9090']
  
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']
    metrics_path: '/metrics'
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
      - source_labels: [__address__]
        target_label: __param_target
      - target_label: __address__
        replacement: 'node-exporter:9100'

  - job_name: 'odoo'
    metrics_path: '/metrics'
    static_configs:
    - targets: ['192.168.56.12:9100']

  - job_name: 'postgresql'
    static_configs:
      - targets: ['192.168.56.10:9187']

remote_write:
  - url: "http://192.168.56.10:9187/api/v1/write"